Disabilities metrics tests
scarletstudio/transithealth pull request #69
Opened 2021-07-17 18:20 UTC by MariaGarciaCS

The tests for the disability rate metric all pass, but two other tests do not. 

```
pipeline/tests/database_test.py::test_table_counts FAILED
pipeline/tests/database_test.py::test_belonging FAILED 
```

I updated my repo following the thread in "#help" between Vinesh and Asude, but the tests continue to fail. The only file I modified is community_test.py

2021-07-17 18:23 UTC, vingkan commented on api/metrics/community_test.py
> +        },
Good test! I would add one more row with a segment that is not "all" to show that the segment filter works.

2021-07-17 18:25 UTC, vingkan requested changes
Thanks for adding this test! GitHub says your tests pass and I pulled your branch to run tests on my Cloud9 and they pass there as well.

I suggested one change to the input data for your test. After you make that change you can merge.

2021-07-18 20:46 UTC, MariaGarciaCS commented
Test for segment filter has been added. All tests pass.

2021-07-18 20:49 UTC, vingkan approved these changes
Good to merge! Thanks for updating the test.

Based on the diff, it seems like your PR changed the compressed database file even though it shouldn't have. The tests pass, so it's probably an safe change, and we don't have an easy way to fix that after it's been committed. So let's go ahead and merge it for now.

2021-07-18 20:54 UTC, merged